// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteResourceBadRequestCode is the HTTP code returned for type DeleteResourceBadRequest
const DeleteResourceBadRequestCode int = 400

/*DeleteResourceBadRequest Invalid ID supplied

swagger:response deleteResourceBadRequest
*/
type DeleteResourceBadRequest struct {
}

// NewDeleteResourceBadRequest creates DeleteResourceBadRequest with default headers values
func NewDeleteResourceBadRequest() *DeleteResourceBadRequest {
	return &DeleteResourceBadRequest{}
}

// WriteResponse to the client
func (o *DeleteResourceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteResourceNotFoundCode is the HTTP code returned for type DeleteResourceNotFound
const DeleteResourceNotFoundCode int = 404

/*DeleteResourceNotFound resource not found

swagger:response deleteResourceNotFound
*/
type DeleteResourceNotFound struct {
}

// NewDeleteResourceNotFound creates DeleteResourceNotFound with default headers values
func NewDeleteResourceNotFound() *DeleteResourceNotFound {
	return &DeleteResourceNotFound{}
}

// WriteResponse to the client
func (o *DeleteResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
