// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/TMaYaD/reservoir/models"
)

// GetResourceOKCode is the HTTP code returned for type GetResourceOK
const GetResourceOKCode int = 200

/*GetResourceOK successful operation

swagger:response getResourceOK
*/
type GetResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewGetResourceOK creates GetResourceOK with default headers values
func NewGetResourceOK() *GetResourceOK {
	return &GetResourceOK{}
}

// WithPayload adds the payload to the get resource o k response
func (o *GetResourceOK) WithPayload(payload *models.Resource) *GetResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resource o k response
func (o *GetResourceOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourceBadRequestCode is the HTTP code returned for type GetResourceBadRequest
const GetResourceBadRequestCode int = 400

/*GetResourceBadRequest Invalid ID supplied

swagger:response getResourceBadRequest
*/
type GetResourceBadRequest struct {
}

// NewGetResourceBadRequest creates GetResourceBadRequest with default headers values
func NewGetResourceBadRequest() *GetResourceBadRequest {
	return &GetResourceBadRequest{}
}

// WriteResponse to the client
func (o *GetResourceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetResourceNotFoundCode is the HTTP code returned for type GetResourceNotFound
const GetResourceNotFoundCode int = 404

/*GetResourceNotFound Resource not found

swagger:response getResourceNotFound
*/
type GetResourceNotFound struct {
}

// NewGetResourceNotFound creates GetResourceNotFound with default headers values
func NewGetResourceNotFound() *GetResourceNotFound {
	return &GetResourceNotFound{}
}

// WriteResponse to the client
func (o *GetResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
