// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/TMaYaD/reservoir/models"
)

// UpdateResourceWithFormOKCode is the HTTP code returned for type UpdateResourceWithFormOK
const UpdateResourceWithFormOKCode int = 200

/*UpdateResourceWithFormOK successful operation

swagger:response updateResourceWithFormOK
*/
type UpdateResourceWithFormOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewUpdateResourceWithFormOK creates UpdateResourceWithFormOK with default headers values
func NewUpdateResourceWithFormOK() *UpdateResourceWithFormOK {
	return &UpdateResourceWithFormOK{}
}

// WithPayload adds the payload to the update resource with form o k response
func (o *UpdateResourceWithFormOK) WithPayload(payload *models.Resource) *UpdateResourceWithFormOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update resource with form o k response
func (o *UpdateResourceWithFormOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateResourceWithFormOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateResourceWithFormNotFoundCode is the HTTP code returned for type UpdateResourceWithFormNotFound
const UpdateResourceWithFormNotFoundCode int = 404

/*UpdateResourceWithFormNotFound Resource not found

swagger:response updateResourceWithFormNotFound
*/
type UpdateResourceWithFormNotFound struct {
}

// NewUpdateResourceWithFormNotFound creates UpdateResourceWithFormNotFound with default headers values
func NewUpdateResourceWithFormNotFound() *UpdateResourceWithFormNotFound {
	return &UpdateResourceWithFormNotFound{}
}

// WriteResponse to the client
func (o *UpdateResourceWithFormNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateResourceWithFormMethodNotAllowedCode is the HTTP code returned for type UpdateResourceWithFormMethodNotAllowed
const UpdateResourceWithFormMethodNotAllowedCode int = 405

/*UpdateResourceWithFormMethodNotAllowed Invalid input

swagger:response updateResourceWithFormMethodNotAllowed
*/
type UpdateResourceWithFormMethodNotAllowed struct {
}

// NewUpdateResourceWithFormMethodNotAllowed creates UpdateResourceWithFormMethodNotAllowed with default headers values
func NewUpdateResourceWithFormMethodNotAllowed() *UpdateResourceWithFormMethodNotAllowed {
	return &UpdateResourceWithFormMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateResourceWithFormMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
