// Code generated by go-swagger; DO NOT EDIT.

package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateResourceWithFormHandlerFunc turns a function with the right signature into a update resource with form handler
type UpdateResourceWithFormHandlerFunc func(UpdateResourceWithFormParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateResourceWithFormHandlerFunc) Handle(params UpdateResourceWithFormParams) middleware.Responder {
	return fn(params)
}

// UpdateResourceWithFormHandler interface for that can handle valid update resource with form params
type UpdateResourceWithFormHandler interface {
	Handle(UpdateResourceWithFormParams) middleware.Responder
}

// NewUpdateResourceWithForm creates a new http.Handler for the update resource with form operation
func NewUpdateResourceWithForm(ctx *middleware.Context, handler UpdateResourceWithFormHandler) *UpdateResourceWithForm {
	return &UpdateResourceWithForm{Context: ctx, Handler: handler}
}

/*UpdateResourceWithForm swagger:route POST /resource/{template} resource updateResourceWithForm

Updates a resource with form data

*/
type UpdateResourceWithForm struct {
	Context *middleware.Context
	Handler UpdateResourceWithFormHandler
}

func (o *UpdateResourceWithForm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateResourceWithFormParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
