// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/tls"
	"net/http"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	graceful "github.com/tylerb/graceful"

	"github.com/TMaYaD/reservoir/restapi/operations"
	"github.com/TMaYaD/reservoir/restapi/operations/claim"
	"github.com/TMaYaD/reservoir/restapi/operations/resource"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name  --spec ../swagger.yaml

func configureFlags(api *operations.ReservoirAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.ReservoirAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.UrlformConsumer = runtime.DiscardConsumer

	api.JSONProducer = runtime.JSONProducer()

	api.ResourceAddResourceHandler = resource.AddResourceHandlerFunc(func(params resource.AddResourceParams) middleware.Responder {
		return middleware.NotImplemented("operation resource.AddResource has not yet been implemented")
	})
	api.ClaimClaimResourceHandler = claim.ClaimResourceHandlerFunc(func(params claim.ClaimResourceParams) middleware.Responder {
		return middleware.NotImplemented("operation claim.ClaimResource has not yet been implemented")
	})
	api.ResourceDeleteResourceHandler = resource.DeleteResourceHandlerFunc(func(params resource.DeleteResourceParams) middleware.Responder {
		return middleware.NotImplemented("operation resource.DeleteResource has not yet been implemented")
	})
	api.ClaimGetClaimHandler = claim.GetClaimHandlerFunc(func(params claim.GetClaimParams) middleware.Responder {
		return middleware.NotImplemented("operation claim.GetClaim has not yet been implemented")
	})
	api.ResourceGetResourceHandler = resource.GetResourceHandlerFunc(func(params resource.GetResourceParams) middleware.Responder {
		return middleware.NotImplemented("operation resource.GetResource has not yet been implemented")
	})
	api.ResourceListResourcesHandler = resource.ListResourcesHandlerFunc(func(params resource.ListResourcesParams) middleware.Responder {
		return middleware.NotImplemented("operation resource.ListResources has not yet been implemented")
	})
	api.ClaimReleaseClaimHandler = claim.ReleaseClaimHandlerFunc(func(params claim.ReleaseClaimParams) middleware.Responder {
		return middleware.NotImplemented("operation claim.ReleaseClaim has not yet been implemented")
	})
	api.ResourceSetResourceHandler = resource.SetResourceHandlerFunc(func(params resource.SetResourceParams) middleware.Responder {
		return middleware.NotImplemented("operation resource.SetResource has not yet been implemented")
	})
	api.ResourceUpdateResourceWithFormHandler = resource.UpdateResourceWithFormHandlerFunc(func(params resource.UpdateResourceWithFormParams) middleware.Responder {
		return middleware.NotImplemented("operation resource.UpdateResourceWithForm has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
