// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Reservoir
Reservoir is a resource manager with support for wildcards

Terms Of Service:

http://lexent.bio/terms/


    Schemes:
      https
    Host: reservoir.lexent.bio
    BasePath: /api/v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <schandra@lexenbio.com>

    Consumes:
    - application/x-www-form-urlencoded

    Produces:
    - application/json

swagger:meta
*/
package restapi
