// Code generated by go-swagger; DO NOT EDIT.

package claim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ClaimResourceHandlerFunc turns a function with the right signature into a claim resource handler
type ClaimResourceHandlerFunc func(ClaimResourceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ClaimResourceHandlerFunc) Handle(params ClaimResourceParams) middleware.Responder {
	return fn(params)
}

// ClaimResourceHandler interface for that can handle valid claim resource params
type ClaimResourceHandler interface {
	Handle(ClaimResourceParams) middleware.Responder
}

// NewClaimResource creates a new http.Handler for the claim resource operation
func NewClaimResource(ctx *middleware.Context, handler ClaimResourceHandler) *ClaimResource {
	return &ClaimResource{Context: ctx, Handler: handler}
}

/*ClaimResource swagger:route POST /claim claim claimResource

Place a claim for a given name

*/
type ClaimResource struct {
	Context *middleware.Context
	Handler ClaimResourceHandler
}

func (o *ClaimResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewClaimResourceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
