// Code generated by go-swagger; DO NOT EDIT.

package claim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/TMaYaD/reservoir/models"
)

// GetClaimOKCode is the HTTP code returned for type GetClaimOK
const GetClaimOKCode int = 200

/*GetClaimOK successful operation

swagger:response getClaimOK
*/
type GetClaimOK struct {

	/*
	  In: Body
	*/
	Payload *models.Claim `json:"body,omitempty"`
}

// NewGetClaimOK creates GetClaimOK with default headers values
func NewGetClaimOK() *GetClaimOK {
	return &GetClaimOK{}
}

// WithPayload adds the payload to the get claim o k response
func (o *GetClaimOK) WithPayload(payload *models.Claim) *GetClaimOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get claim o k response
func (o *GetClaimOK) SetPayload(payload *models.Claim) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClaimOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClaimBadRequestCode is the HTTP code returned for type GetClaimBadRequest
const GetClaimBadRequestCode int = 400

/*GetClaimBadRequest Invalid ID supplied

swagger:response getClaimBadRequest
*/
type GetClaimBadRequest struct {
}

// NewGetClaimBadRequest creates GetClaimBadRequest with default headers values
func NewGetClaimBadRequest() *GetClaimBadRequest {
	return &GetClaimBadRequest{}
}

// WriteResponse to the client
func (o *GetClaimBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetClaimNotFoundCode is the HTTP code returned for type GetClaimNotFound
const GetClaimNotFoundCode int = 404

/*GetClaimNotFound Order not found

swagger:response getClaimNotFound
*/
type GetClaimNotFound struct {
}

// NewGetClaimNotFound creates GetClaimNotFound with default headers values
func NewGetClaimNotFound() *GetClaimNotFound {
	return &GetClaimNotFound{}
}

// WriteResponse to the client
func (o *GetClaimNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
